### ISSUE TITLE
zerotier service isn't enabled bug

### ISSUE THREAD

**Issue by whyiseveryfuckingnameisalreadyused** [tralph3/ZeroTier-GUI#16]
i'm getting this error every time i want to use zerotier-gui, but zerotier-one service is running, and works perfectly through cli.
i'm using zerotier-gui-git from aur

![Screenshot_2021-09-30_00-05-06](https://user-images.githubusercontent.com/91638004/135355085-b4b4d409-b2d7-4a63-aa36-051986bd0bfc.png)

**Comment by tralph3** [comment]
Weird, could you show the output of `zerotier-cli`?

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
```
ZeroTier One version 1.6.6 build 0 (platform 1 arch 2)
Copyright (c) 2020 ZeroTier, Inc.
Licensed under the ZeroTier BSL 1.1 (see LICENSE.txt)
Usage: zerotier-cli [-switches] <command/path> [<args>]

Available switches:
  -h                      - Display this help
  -v                      - Show version
  -j                      - Display full raw JSON output
  -D<path>                - ZeroTier home path for parameter auto-detect
  -p<port>                - HTTP port (default: auto)
  -T<token>               - Authentication token (default: auto)

Available commands:
  info                    - Display status info
  listpeers               - List all peers
  peers                   - List all peers (prettier)
  listnetworks            - List all networks
  join <network ID>          - Join a network
  leave <network ID>         - Leave a network
  set <network ID> <setting> - Set a network setting
  get <network ID> <setting> - Get a network setting
  listmoons               - List moons (federated root sets)
  orbit <world ID> <seed> - Join a moon via any member root
  deorbit <world ID>      - Leave a moon
  dump                    - Debug settings dump for support

Available settings:
  Settings to use with [get/set] may include property names from 
  the JSON output of "zerotier-cli -j listnetworks". Additionally, 
  (ip, ip4, ip6, ip6plane, and ip6prefix can be used). For instance:
  zerotier-cli get <network ID> ip6plane will return the 6PLANE address
  assigned to this node.

```

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
> Weird, could you show the output of `zerotier-cli`?

**Comment by tralph3** [comment]
Does `zerotier-cli -j listnetworks` work?

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
it seems to work
```
[
 {
  "allowDNS": false,
  "allowDefault": false,
  "allowGlobal": false,
  "allowManaged": true,
  "assignedAddresses": [
   "192.168.193.168/24"
  ],
  "bridge": false,
  "broadcastEnabled": true,
  "dhcp": false,
  "dns": {
   "domain": "",
   "servers": []
  },
  "id": "abfd31bd473197bb",
  "mac": "ba:38:3f:6d:28:d4",
  "mtu": 2800,
  "multicastSubscriptions": [
   {
    "adi": 0,
    "mac": "01:00:5e:00:00:01"
   },
   {
    "adi": 0,
    "mac": "01:00:5e:00:00:fb"
   },
   {
    "adi": 0,
    "mac": "33:33:00:00:00:01"
   },
   {
    "adi": 0,
    "mac": "33:33:00:00:00:fb"
   },
   {
    "adi": 0,
    "mac": "33:33:ff:8e:74:3f"
   },
   {
    "adi": 3232285096,
    "mac": "ff:ff:ff:ff:ff:ff"
   }
  ],
  "name": "high_shockley",
  "netconfRevision": 1,
  "nwid": "abfd31bd473197bb",
  "portDeviceName": "ztc25aakx4",
  "portError": 0,
  "routes": [
   {
    "flags": 0,
    "metric": 0,
    "target": "192.168.193.0/24",
    "via": null
   }
  ],
  "status": "OK",
  "type": "PUBLIC"
 }
]

```

**Comment by tralph3** [comment]
Try running `zerotier-gui` in the terminal, see if there's some output that may be useful there.

**Comment by tralph3** [comment]
If the `zerotier-cli` commands are working... the gui shouldn't be throwing that error.

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
this is the output after i clicked yes on enabling zerotier service
```
Traceback (most recent call last):
  File "/usr/bin/zerotier-gui", line 919, in <module>
    mainWindow = MainWindow().window
  File "/usr/bin/zerotier-gui", line 116, in __init__
    self.refresh_networks()
  File "/usr/bin/zerotier-gui", line 234, in refresh_networks
    networkData = self.get_networks_info()
  File "/usr/bin/zerotier-gui", line 276, in get_networks_info
    return json.loads(check_output(['zerotier-cli', '-j', 'listnetworks']))
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['zerotier-cli', '-j', 'listnetworks']' returned non-zero exit status 1.

```

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
does zerotier-gui keeps something in my home directory? it worked fine before i reinstalled my system, but i kept most of the content of my $home

**Comment by tralph3** [comment]
Do you have the `.zeroTierOneAuthToken` file in your home directory?

**Comment by tralph3** [comment]
Ahh... that may be the issue... if you have that file, delete it and restart the gui.

**Comment by whyiseveryfuckingnameisalreadyused** [comment]
that was it, thanks.

**Comment by tralph3** [comment]
no problem
